name: Commitlint
on:
  pull_request: { branches: ['**'] }
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm install --no-save @commitlint/config-conventional @commitlint/cli
      - if: github.event_name == 'pull_request'
        run: npx commitlint --from "${{ github.event.pull_request.base.sha }}" --to "${{ github.event.pull_request.head.sha }}"
      - if: github.event_name == 'push'
        run: npx commitlint --from "${{ github.event.before }}" --to "${{ github.sha }}"
